version: "3.9"

services:
  postgresdb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes: 
      - my-db:/var/lib/postgresql/data

volumes:
  my-db: